### PR TITLE
Allow the fixed fonts to be scaled up.

### LINKED ISSUE #3: Add API to set font size
From @tigoe:

> To set. One of the big issues I've found is readability of different fonts across different screens (been testing ePaper too), so having the ability to adapt fonts and sizes is essential.

### LINKED ISSUE #46: Issues with void ArduinoGraphics::image(const Image& img, int x, int y, int width, int height)
```
void ArduinoGraphics::image(const Image& img, int x, int y, int width, int height)
{
  if (!img || ((x + width) < 0) || ((y + height) < 0) || (x > _width) || (y > height)) {
    // offscreen
    return;
  }
...
```
The first issue I ran into is there is an error/typo in the check for proper ranges...
The line should be:
```
  if (!img || ((x + width) < 0) || ((y + height) < 0) || (x > _width) || (y > _height)) {
```
That is, you should be testing against the height of the display, not the height of the image passed in.

Another issue I have run into, is in the RGB format the order of the bytes:  
That is in my own code potentially calling it:

```
void writeClippedRect24(int16_t x, int16_t y, int16_t cx, int16_t cy, uint32_t *pixels) {
    y += g_image_offset_y;
    x += g_image_offset_x;
#if 1
    Image img(ENCODING_RGB, (uint8_t *)pixels, cx, cy);
    Display.image(img, x, y, cx, cy);
#else
    //Display.image(img, x, y);
    for (int16_t iy = y; iy < (y + cy); iy++) {
        for (int16_t ix = x; ix < (x + cx); ix++) {
            uint32_t color = *pixels++;
            Display.set(ix, iy, color >> 16, color >> 8, color);
        }
    }
#endif    
}
```
Where the RGB bytes are within the uint32_t is different.  Mine is setup to handle the order of bytes
returned by JPEGDEC RGB8888 format where Alpha is the high byte  and the code in 
```
void ArduinoGraphics::imageRGB(const Image& img, int x, int y, int width, int height)
{
  const uint8_t* data = img.data();

  for (int j = 0; j < height; j++) {
    for (int i = 0; i < width; i++) {
      uint8_t r = *data++;
      uint8_t g = *data++;
      uint8_t b = *data++;

      set(x + i, y + j, r, g, b);

      data++;
    }

    data += (4 * (img.width() - width));
  }
}
```
Assumes that it is the 4th byte that is skipped.  Not sure of best fix for this.  For me just changing back to my own code
works.  Alternative is to either change the library by changing the skipped byte or by adding different image type

### PR DESCRIPTION
**Pull request by KurtE**
This hopefully addresses issue #3 

On larger displays, the two built in fonts are almost invisible. One possible solution is to supply some larger fonts.

Another approach is to do, like several TFT display drivers do and allow you to scale the system fixed fonts up to a larger size.  Decided this was the easiest approach, and did a quick implementation of it.  Like the Adafruit displays, I allowed you to set different scale factors for X and Y.

I added a scaledBitmap function which is a modified version of the current bitmap function.  I also changed all of the text functions to use it.  I left the unscalled version of the API, although I have it simply call the scaled version with scales 1 and 1, as since these methods are virtual, potentially some other subclasses might use and/or implement their own version.

Updated the textFontWidth and textFontHeight to multiply  the height * the scale as the one example sketch here needs it.

I also updated the sketch to scale the canvas to take the font size into account. This appears to work with the changes and

I have not used or tested the scroll code.  Its sizing should be updated teh same way the test sketch was with the changes with the textFontWidth and textFontHeight changes

### CODE REVIEW

**Comment by KurtE** [comment]
As I mentioned in the forum thread:
https://forum.arduino.cc/t/arduino-h7-video-h-and-arduinographics-library-fonts/1289636/3?u=kurte

I have run what tests I know of for this library.  I believe there are integration issues between this library and 
the Arduino_H7_Video library, but that is caused by these changes.  So I will go ahead and mark it ready for review

File: src/ArduinoGraphics.h [hunk 1]
```diff
@@ -114,6 +118,8 @@ class ArduinoGraphics : public Print {
   uint8_t _textR, _textG, _textB;
   int _textX;
   int _textY;
+  uint8_t _textsize_x;
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
  uint8_t _textSizeX;
```

File: src/ArduinoGraphics.h [hunk 2]
```diff
@@ -114,6 +118,8 @@ class ArduinoGraphics : public Print {
...
+  uint8_t _textsize_y;
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
  uint8_t _textSizeY;
```

File: src/ArduinoGraphics.h [hunk 3]
```diff
@@ -92,6 +94,8 @@ class ArduinoGraphics : public Print {
 
 protected:
   virtual void bitmap(const uint8_t* data, int x, int y, int width, int height);
+  virtual void scaledBitmap(const uint8_t* data, int x, int y, int width, int height,
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
```

File: src/ArduinoGraphics.h [hunk 4]
```diff
@@ -92,6 +94,8 @@ class ArduinoGraphics : public Print {
 
 protected:
   virtual void bitmap(const uint8_t* data, int x, int y, int width, int height);
+  virtual void scaledBitmap(const uint8_t* data, int x, int y, int width, int height, 
+                            uint8_t scale_x, uint8_t);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
```

File: src/ArduinoGraphics.h [hunk 5]
```diff
@@ -92,6 +94,8 @@ class ArduinoGraphics : public Print {
 
 protected:
   virtual void bitmap(const uint8_t* data, int x, int y, int width, int height);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
  virtual void bitmap(const uint8_t* data, int x, int y, int w, int h, uint8_t scale_x = 1, uint8_t scale_y = 1);
```

File: src/ArduinoGraphics.h [hunk 6]
```diff
@@ -70,6 +70,8 @@ class ArduinoGraphics : public Print {
   virtual void text(const char* str, int x = 0, int y = 0);
   virtual void text(const String& str, int x = 0, int y = 0) { text(str.c_str(), x, y); }
   virtual void textFont(const Font& which);
+  virtual void setTextSize(uint8_t s) {setTextSize(s, s);}
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
  virtual void textSize(uint8_t s) {textSize(s, s);}
```

File: src/ArduinoGraphics.h [hunk 7]
```diff
@@ -70,6 +70,8 @@ class ArduinoGraphics : public Print {
...
+  virtual void setTextSize(uint8_t sx, uint8_t sy);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.h]:
```suggestion
  virtual void textSize(uint8_t sx, uint8_t sy);
```

File: src/ArduinoGraphics.cpp [hunk 8]
```diff
@@ -474,7 +495,7 @@ void ArduinoGraphics::endText(int scrollDirection)
       beginDraw();
       int const text_y = _textY - (scrollLength - i - 1);
       text(_textBuffer, _textX, text_y);
-      bitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1);
+      scaledBitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1, _textsize_x, _textsize_y);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      bitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1, _textSizeX, _textSizeY);
```

File: src/ArduinoGraphics.cpp [hunk 9]
```diff
@@ -462,7 +483,7 @@ void ArduinoGraphics::endText(int scrollDirection)
       beginDraw();
       int const text_y = _textY - i;
       text(_textBuffer, _textX, text_y);
-      bitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1);
+      scaledBitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1, _textsize_x, _textsize_y);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      bitmap(_font->data[0x20], _textX, text_y - 1, _font->width, 1, _textSizeX, _textSizeY);
```

File: src/ArduinoGraphics.cpp [hunk 10]
```diff
@@ -450,7 +471,7 @@ void ArduinoGraphics::endText(int scrollDirection)
       beginDraw();
       int const text_x = _textX - (scrollLength - i - 1);
       text(_textBuffer, text_x, _textY);
-      bitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height);
+      scaledBitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height, _textsize_x, _textsize_y);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      bitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height, _textSizeX, _textSizeY);
```

File: src/ArduinoGraphics.cpp [hunk 11]
```diff
@@ -438,7 +459,7 @@ void ArduinoGraphics::endText(int scrollDirection)
       beginDraw();
       int const text_x = _textX - i;
       text(_textBuffer, text_x, _textY);
-      bitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height);
+      scaledBitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height, _textsize_x, _textsize_y);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      bitmap(_font->data[0x20], text_x - 1, _textY, 1, _font->height, _textSizeX, _textSizeY);
```

File: src/ArduinoGraphics.cpp [hunk 12]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
...
+  return (_font ? _font->height* _textsize_y : 0);
 }
 
+void ArduinoGraphics::setTextSize(uint8_t sx, uint8_t sy)
+{
+  _textsize_x = (sx > 0)? sx : 1;
+  _textsize_y = (sy > 0)? sy : 1;
+}
+
+
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp:288]:
```suggestion
```

File: src/ArduinoGraphics.cpp [hunk 13]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
...
 int ArduinoGraphics::textFontHeight() const
 {
-  return (_font ? _font->height : 0);
+  return (_font ? _font->height* _textsize_y : 0);
 }
 
+void ArduinoGraphics::setTextSize(uint8_t sx, uint8_t sy)
+{
+  _textsize_x = (sx > 0)? sx : 1;
+  _textsize_y = (sy > 0)? sy : 1;
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
  _textSizeX = (sx > 0)? sx : 1;
  _textSizeY = (sy > 0)? sy : 1;
```

File: src/ArduinoGraphics.cpp [hunk 14]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
...
 int ArduinoGraphics::textFontWidth() const
 {
-  return (_font ? _font->width : 0);
+  return (_font ? _font->width * _textsize_x : 0);
 }
 
 int ArduinoGraphics::textFontHeight() const
 {
-  return (_font ? _font->height : 0);
+  return (_font ? _font->height* _textsize_y : 0);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
  return (_font ? _font->height * _textSizeY : 0);
```

File: src/ArduinoGraphics.cpp [hunk 15]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
 
 int ArduinoGraphics::textFontWidth() const
 {
-  return (_font ? _font->width : 0);
+  return (_font ? _font->width * _textsize_x : 0);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
  return (_font ? _font->width * _textSizeX : 0);
```

File: src/ArduinoGraphics.cpp [hunk 16]
```diff
@@ -254,10 +256,10 @@ void ArduinoGraphics::text(const char* str, int x, int y)
       }
 
       if (b) {
-        bitmap(b, x, y, _font->width, _font->height);
+        scaledBitmap(b, x, y, _font->width, _font->height, _textsize_x, _textsize_y);
       }
 
-      x += _font->width;
+      x += _font->width * _textsize_x;
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      x += _font->width * _textSizeX;
```

File: src/ArduinoGraphics.cpp [hunk 17]
```diff
@@ -254,10 +256,10 @@ void ArduinoGraphics::text(const char* str, int x, int y)
       }
 
       if (b) {
-        bitmap(b, x, y, _font->width, _font->height);
+        scaledBitmap(b, x, y, _font->width, _font->height, _textsize_x, _textsize_y);
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
        bitmap(b, x, y, _font->width, _font->height, _textSizeX, _textSizeY);
```

File: src/ArduinoGraphics.cpp [hunk 18]
```diff
@@ -241,7 +243,7 @@ void ArduinoGraphics::text(const char* str, int x, int y)
     uint8_t const c = (uint8_t)*str++;
 
     if (c == '\n') {
-      y += _font->height;
+      y += _font->height * _textsize_y;
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
      y += _font->height * _textSizeY;
```

File: src/ArduinoGraphics.cpp [hunk 19]
```diff
@@ -26,7 +26,9 @@
 ArduinoGraphics::ArduinoGraphics(int width, int height) :
   _width(width),
   _height(height),
-  _font(NULL)
+  _font(NULL),
+  _textsize_x(1),
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
  _textSizeX(1),
```

File: src/ArduinoGraphics.cpp [hunk 20]
```diff
@@ -26,7 +26,9 @@
...
+  _textsize_y(1)
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
  _textSizeY(1)
```

File: examples/ASCIIDraw/ASCIIDraw.ino [hunk 21]
```diff
@@ -85,6 +86,7 @@ void setup() {
   ASCIIDraw.stroke('@', 0, 0);
   const char text[] = "ARDUINO";
   ASCIIDraw.textFont(Font_5x7);
+  ASCIIDraw.setTextSize(fontSize);
```
Comment (leonardocavagnis) [inline examples/ASCIIDraw/ASCIIDraw.ino]:
```suggestion
  ASCIIDraw.textSize(fontSize);
```

File: src/ArduinoGraphics.cpp [hunk 22]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
...
+
+
 void ArduinoGraphics::bitmap(const uint8_t* data, int x, int y, int width, int height)
 {
-  if (!_stroke) {
+  // forward to scaled version
+  scaledBitmap(data, x, y, width, height, 1, 1);
+}
+
+void ArduinoGraphics::scaledBitmap(const uint8_t* data, int x, int y, int w, int h, uint8_t scale_x, uint8_t scale_y) {
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
```

File: src/ArduinoGraphics.cpp [hunk 23]
```diff
@@ -269,38 +271,57 @@ void ArduinoGraphics::textFont(const Font& which)
...
 }
 
+void ArduinoGraphics::setTextSize(uint8_t sx, uint8_t sy)
+{
+  _textsize_x = (sx > 0)? sx : 1;
+  _textsize_y = (sy > 0)? sy : 1;
+}
+
+
 void ArduinoGraphics::bitmap(const uint8_t* data, int x, int y, int width, int height)
```
Comment (leonardocavagnis) [inline src/ArduinoGraphics.cpp]:
```suggestion
void ArduinoGraphics::bitmap(const uint8_t* data, int x, int y, int w, int h, uint8_t scale_x, uint8_t scale_y)
```

**Review by leonardocavagnis — CHANGES_REQUESTED** [review]
The changes look good!

Some adjustments for consistency:
- `_textsize_x, _textsize_y` -> `_textSizeX, _textSizeY`
- `setTextSize()` -> `textSize()`
- remove `scaledBitmap` function, and overload `bitmap` with default values

File: src/ArduinoGraphics.cpp (hunk 23 above)
Comment (KurtE) [reply src/ArduinoGraphics.cpp]: I believe I pushed up the changes that were requested.
First attempt forgot to update the example sketch.

Let me know if I missed anything.

**Comment by leonardocavagnis** [comment]
Thank you for the changes! 
Could you please rebase and merge the modifications into a single commit? Also, could you update the [API documentation](https://github.com/arduino-libraries/ArduinoGraphics/blob/master/docs/api.md) to include the `textSize` function?

**Comment by KurtE** [comment]
Pushed up changes and squashed all down to 1...
